# Currently experimental.
name: 'osv-scanner'
description: 'Scans your directory against the OSV database (Experimental)'
inputs:
  to-scan:
    description: 'Directories to scan'
    required: false
    default: "./"
  results-file:
    description: 'OUTPUT: Path to file to store results'
    required: true
  results-format:
    description: 'Output result format'
    required: false
    default: 'report'
  recursive-search:
    description: 'Recursively scan though subdirectories'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'ghcr.io/another-rex/osv-scanner:markdown-test'
  args:
    - '--skip-git'
    - '--output=${{ inputs.results-file }}'
    - '--format=${{ inputs.results-format }}'
    - '--recursive=${{ inputs.recursive-search}}'
    - ${{ inputs.to-scan }}
