# Currently experimental.
name: 'osv-scanner'
description: 'Scans your directory against the OSV database (Experimental)'
inputs:
  to-scan:
    description: 'Directory to scan'
    required: false
    default: '/github/workspace'
  results_file:
    description: "OUTPUT: Path to file to store results"
    required: true
  results_format:
    description: "Output result format"
    required: false
    default: 'report'
runs:
  using: 'docker'
  image: 'ghcr.io/google/osv-scanner:v1.3.4'
  args:
    - '--skip-git'
    - '--format ${{ inputs.results_format }}'
    - '--output ${{ inputs.results_file }}'
    - '-r'
    - ${{ inputs.to-scan }}
