name: Check links on push

on: push

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  markdown-link-check:
    permissions:
      contents: read # to fetch code (actions/checkout)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: gaurav-nelson/github-action-markdown-link-check@25b2c436c653f0d4500d3c2df86e5c14e71e44e1
        with:
          use-quiet-mode: "yes"
          base-branch: "main"
          check-modified-files-only: "yes"
# Documentation available here: https://github.com/marketplace/actions/markdown-link-check
