# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: OSV-Scanner PR scanning

on:
  workflow_call:

jobs:
  scan-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Get changed files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v37

      #     # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      #     # with:
      #     #   since_last_remote_commit: true 

      # - name: List all changed files
      #   run: |
      #     echo ${{ steps.changed-files.outputs.all_changed_files }}
      #     echo ------------
      #     for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
      #       echo "$file was changed"
      #     done
      - name: "Checkout target branch"
        run: git checkout $GITHUB_BASE_REF
      - name: "Run scanner"
        uses: another-rex/osv-scanner@markdown-output
        continue-on-error: true
        with:
          results-format: json
          results-file: old-result.json
          to-scan: .
          recursive-search: true
      - name: "Checkout current branch"
        run: git checkout $GITHUB_SHA
      - name: "Run scanner"
        uses: another-rex/osv-scanner@markdown-output
        with:
          results-format: sarif
          results-file: results.sarif
          to-scan: .
          recursive-search: true
          old-results: old-result.json
      # Upload the results as artifacts (optional). Commenting out will disable uploads of run results in SARIF
      # format to the repository Actions tab.
      - name: "Upload artifact"
        if: '!cancelled()'
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: "Upload artifact 2"
        if: '!cancelled()'
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: Old result
          path: old-result.json
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        if: '!cancelled()'
        uses: github/codeql-action/upload-sarif@6c089f53dd51dc3fc7e599c3cb5356453a52ca9e # v2.20.0
        with:
          sarif_file: results.sarif

